#!/usr/bin/env python3
"""Transcribe a session recording with WhisperX, biased by campaign vocabulary,
and write a speaker-attributed Markdown transcript to transcripts/.

Pipeline:
    audio -> whisper-large-v3 -> wav2vec2 alignment -> pyannote diarization
          -> SPEAKER_XX -> player names (via config.speaker_map)
          -> transcripts/NNN-raw.md

Usage:
    python tools/whisperx/transcribe.py recordings/session-019.wav
    python tools/whisperx/transcribe.py recordings/019.wav --session 19
    python tools/whisperx/transcribe.py path/to/audio.wav --config tools/whisperx/config.json
"""

from __future__ import annotations

import argparse
import datetime as dt
import json
import os
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_CONFIG = Path(__file__).parent / "config.json"
EXAMPLE_CONFIG = Path(__file__).parent / "config.example.json"

SESSION_NUM_RE = re.compile(r"(\d{1,4})")


def load_config(path: Path) -> dict:
    if not path.exists():
        if EXAMPLE_CONFIG.exists():
            print(
                f"[transcribe] {path} not found. Copy {EXAMPLE_CONFIG.name} to "
                f"config.json and edit it.",
                file=sys.stderr,
            )
        sys.exit(2)
    return json.loads(path.read_text(encoding="utf-8"))


def infer_session_number(audio_path: Path, override: int | None) -> int:
    if override is not None:
        return override
    m = SESSION_NUM_RE.search(audio_path.stem)
    if not m:
        print(
            f"[transcribe] Could not infer session number from filename "
            f"{audio_path.name!r}. Pass --session N.",
            file=sys.stderr,
        )
        sys.exit(2)
    return int(m.group(1))


def build_vocab(blurb: str = "A Dungeons and Dragons session.") -> tuple[str, str]:
    """Import build_hotwords as a module and reuse its logic."""
    sys.path.insert(0, str(Path(__file__).parent))
    import build_hotwords  # type: ignore[import-not-found]

    entity_names = build_hotwords.collect_entity_names()
    pc_names = build_hotwords.collect_pc_names()
    extras = build_hotwords.collect_extra_vocab(
        Path(__file__).parent / "extra_vocab.txt"
    )
    all_terms = entity_names + extras
    hotwords = build_hotwords.to_hotwords(all_terms)
    return hotwords, build_hotwords.to_initial_prompt(blurb, all_terms, pc_names)


def map_speakers(label: str, speaker_map: dict[str, str]) -> str:
    return speaker_map.get(label, label)


def merge_consecutive(segments: list[dict]) -> list[dict]:
    """Merge consecutive segments from the same speaker into one block."""
    merged: list[dict] = []
    for seg in segments:
        spk = seg.get("speaker", "Unknown")
        text = seg.get("text", "").strip()
        if not text:
            continue
        if merged and merged[-1]["speaker"] == spk:
            merged[-1]["end"] = seg.get("end", merged[-1]["end"])
            merged[-1]["text"] = (merged[-1]["text"].rstrip() + " " + text).strip()
        else:
            merged.append(
                {
                    "speaker": spk,
                    "start": seg.get("start", 0.0),
                    "end": seg.get("end", 0.0),
                    "text": text,
                }
            )
    return merged


def fmt_timestamp(seconds: float) -> str:
    td = dt.timedelta(seconds=int(seconds))
    h, rem = divmod(td.seconds, 3600)
    m, s = divmod(rem, 60)
    return f"{h:02d}:{m:02d}:{s:02d}"


def write_transcript(
    out_path: Path,
    session_num: int,
    audio_path: Path,
    segments: list[dict],
    speaker_map: dict[str, str],
) -> None:
    header = (
        "---\n"
        f"session: {session_num}\n"
        f"date: {dt.date.today().isoformat()}\n"
        f"source_audio: {audio_path.name}\n"
        "status: raw\n"
        "---\n\n"
        f"# Session {session_num:03d} — raw transcript\n\n"
        "Generated by `tools/whisperx/transcribe.py`. To fold into canon:\n"
        "1. Run the `prep/transcript-import` skill to draft `sessions/"
        f"{session_num:03d}-*.md`.\n"
        "2. Then run `prep/sessions` to produce Recap + State deltas.\n\n"
        "---\n\n"
    )

    lines = [header]
    for seg in segments:
        spk = map_speakers(seg["speaker"], speaker_map)
        ts = fmt_timestamp(seg["start"])
        lines.append(f"**[{ts}] {spk}:** {seg['text']}\n")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")


def run_pipeline(audio_path: Path, config: dict) -> list[dict]:
    """Wrap the WhisperX pipeline. Imports are inside the function so the script
    can still print --help and config errors without a heavy CUDA load."""
    import whisperx  # type: ignore[import-not-found]
    from whisperx.diarize import DiarizationPipeline  # type: ignore[import-not-found]

    hotwords, initial_prompt = build_vocab(
        config.get("campaign_blurb", "A Dungeons and Dragons session.")
    )
    print(f"[transcribe] hotwords ({len(hotwords.split())} terms): "
          f"{hotwords[:120]}...", file=sys.stderr)

    device = config.get("device", "cuda")
    compute_type = config.get("compute_type", "float16")
    model_name = config.get("model", "large-v3")
    language = config.get("language", "en")
    batch_size = config.get("batch_size", 16)

    print(f"[transcribe] loading {model_name} on {device} ({compute_type})",
          file=sys.stderr)
    model = whisperx.load_model(
        model_name,
        device=device,
        compute_type=compute_type,
        language=language,
        asr_options={
            "beam_size": 5,
            "best_of": 5,
            "patience": 1.0,
            "initial_prompt": initial_prompt,
            "hotwords": hotwords,
            "suppress_numerals": False,
        },
    )

    print(f"[transcribe] loading audio {audio_path}", file=sys.stderr)
    audio = whisperx.load_audio(str(audio_path))

    print("[transcribe] transcribing...", file=sys.stderr)
    result = model.transcribe(audio, batch_size=batch_size)

    print("[transcribe] aligning timestamps...", file=sys.stderr)
    align_model, align_meta = whisperx.load_align_model(
        language_code=result["language"], device=device
    )
    result = whisperx.align(
        result["segments"], align_model, align_meta, audio, device,
        return_char_alignments=False,
    )

    diar_cfg = config.get("diarization", {})
    hf_token = os.environ.get(config.get("hf_token_env", "HF_TOKEN"))
    if not hf_token:
        print(
            "[transcribe] WARNING: no HF_TOKEN env var; diarization will fail. "
            "Get one at https://huggingface.co/settings/tokens and accept the "
            "pyannote/speaker-diarization-community-1 model terms.",
            file=sys.stderr,
        )

    print("[transcribe] diarizing...", file=sys.stderr)
    diarize_model = DiarizationPipeline(
        model_name=diar_cfg.get(
            "model_name", "pyannote/speaker-diarization-community-1"
        ),
        token=hf_token,
        device=device,
    )
    diarize_kwargs: dict = {}
    if diar_cfg.get("num_speakers") is not None:
        diarize_kwargs["num_speakers"] = diar_cfg["num_speakers"]
    if diar_cfg.get("min_speakers") is not None:
        diarize_kwargs["min_speakers"] = diar_cfg["min_speakers"]
    if diar_cfg.get("max_speakers") is not None:
        diarize_kwargs["max_speakers"] = diar_cfg["max_speakers"]
    diarize_segments = diarize_model(audio, **diarize_kwargs)

    print("[transcribe] assigning speakers...", file=sys.stderr)
    result = whisperx.assign_word_speakers(diarize_segments, result)
    return result["segments"]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("audio", type=Path, help="Path to the session audio file")
    parser.add_argument(
        "--session", type=int, default=None,
        help="Session number (inferred from filename if omitted)",
    )
    parser.add_argument(
        "--config", type=Path, default=DEFAULT_CONFIG,
        help="Path to config.json",
    )
    parser.add_argument(
        "--out", type=Path, default=None,
        help="Output transcript path (default: transcripts/NNN-raw.md)",
    )
    parser.add_argument(
        "--dry-run", action="store_true",
        help="Build hotwords and print config; skip the actual pipeline",
    )
    args = parser.parse_args()

    if not args.audio.exists():
        print(f"[transcribe] audio not found: {args.audio}", file=sys.stderr)
        return 2

    config = load_config(args.config)
    session_num = infer_session_number(args.audio, args.session)

    if args.dry_run:
        hotwords, initial_prompt = build_vocab(
            config.get("campaign_blurb", "A Dungeons and Dragons session.")
        )
        print(json.dumps({
            "session": session_num,
            "audio": str(args.audio),
            "hotwords_term_count": len(hotwords.split()),
            "initial_prompt": initial_prompt,
            "config": config,
        }, indent=2))
        return 0

    segments = run_pipeline(args.audio, config)
    merged = merge_consecutive(segments)

    out = args.out
    if out is None:
        out = REPO_ROOT / config.get("transcripts_dir", "transcripts") / (
            f"{session_num:03d}-raw.md"
        )

    write_transcript(out, session_num, args.audio, merged, config.get("speaker_map", {}))
    print(f"[transcribe] wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
